import type { Metadata } from "next";
import { PrimeReactProvider } from "primereact/api";
import "./globals.css";
import 'primereact/resources/themes/saga-blue/theme.css';
import 'primeicons/primeicons.css';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`antialiased`}>
        <PrimeReactProvider>
          {children}
        </PrimeReactProvider>
      </body>
    </html>
  );
}
